---
title: "One Step Ahead MSE"
author: "Qi Wang"
date: "2023-09-25"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
library(dplyr)
library(tscount)
nsf_dat <- read.csv("D:/77/UCSC/study/Research/temp/NSF_dat/graduate_students_final.csv", header = TRUE)
# nsf_dat <- nsf_dat[-which(nsf_dat$ID %in% c(123961603,160755615,163259611,163259613)),]
```


```{r}
# One step ahead prediction
uni_id <- unique(nsf_dat$ID)
model_order <- rep(NA, length(uni_id))
for (i in 1:length(uni_id)) {
  model_order[i] <- unique(nsf_dat$order[which(nsf_dat$ID==uni_id[i])])
}

one_step_ahead_pred <- matrix(NA, nrow = length(uni_id), ncol = length(1999:2020))
one_step_ahead_resid <- matrix(NA, nrow = length(uni_id), ncol = length(1999:2020))

idx = 1
for (i in uni_id) {
  print(paste("Now doing index ", idx, "out of",length(uni_id)))
  for (j in 1999:2020) {
    model_temp <- tsglm(ts = nsf_dat$y[which(nsf_dat$ID==uni_id[idx])], link = "log", distr = "poisson",
                        model = list(past_obs = 1:model_order[idx]))
    one_step_ahead_pred[idx,j-1998] <- predict(model_temp, n.ahead = 1)$pred
    one_step_ahead_resid[idx,j-1998] <- nsf_dat$y[which(nsf_dat$ID==uni_id[idx] & nsf_dat$year == j+1)] - one_step_ahead_pred[idx,j-1998]
  }
      idx = idx + 1
}

# nsf_dat[which(nsf_dat$ID==uni_id[62] & nsf_dat$year == 2008),]
# nsf_dat[which(nsf_dat$ID==uni_id[417] & nsf_dat$year == 1982),]
# nsf_dat[which(nsf_dat$ID==uni_id[453] & nsf_dat$year == 1974),]
# pivot_wider(nsf_dat, names_from = year, values_from = y)
# Multivariate time series
# learn the RNN
write.csv(one_step_ahead_pred, "D:/77/UCSC/study/Research/temp/NSF_dat/one_step_ahead_pred.csv")
write.csv(one_step_ahead_resid, "D:/77/UCSC/study/Research/temp/NSF_dat/one_step_ahead_res.csv")
```


