 ---
title: "MSE Exploration"
author: "Qi Wang"
date: "2023-09-26"
output: pdf_document
---

```{r setup, include=FALSE}
rm(list = ls())
library(ggplot2)

nsf_wide <- read.csv("D:/77/UCSC/study/Research/temp/NSF_dat/nsf_final_wide.csv", header = TRUE)
nsf_long <- read.csv("D:/77/UCSC/study/Research/temp/NSF_dat/nsf_final_long.csv", header = TRUE)

one_step_pred <- read.csv("D:/77/UCSC/study/Research/temp/NSF_dat/one_step_ahead_pred.csv", header = TRUE)[,-1]
one_step_res <- read.csv("D:/77/UCSC/study/Research/temp/NSF_dat/one_step_ahead_res.csv", header = TRUE)[,-1]


```


```{r}
stanford_wide <- nsf_wide[which(nsf_wide$ID =="243744403"),]
missouri_wide <- nsf_wide[which(nsf_wide$ID =="178396403"),]
stanford_long <- nsf_long[which(nsf_long$ID =="243744403"),]
missouri_long <- nsf_long[which(nsf_long$ID =="178396403"),]
p_stanford <- ggplot() +
  geom_line(aes(x = stanford_long$year, y = stanford_long$y), linewidth = 2) +
   geom_point(aes(x = stanford_long$year, y = stanford_long$y), color = "red", size = 2) +
  labs(title = "Time Series of Stanford University Statistics Graduate Students", x = "Time", y = "Count") +
  theme(plot.title = element_text(hjust = 0.5))


p_missouri <- ggplot() +
  geom_line(aes(x = missouri_long$year, y = missouri_long$y), linewidth = 2) +
   geom_point(aes(x = missouri_long$year, y = missouri_long$y), color = "red", size = 2) +
  labs(title = "Time Series ofUniversity of Missouri(Columbia) Statistics Graduate Students", x = "Time", y = "Count") +
  theme(plot.title = element_text(hjust = 0.5))


```











